recipe: default.v1
language: "en"
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: ConveRTFeaturizer
    model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

policies:
- name: MemoizationPolicy
  max_history: 10
- epochs: 100
  name: TEDPolicy
  max_history: 10
  constrain_similarities: True
- core_fallback_action_name: action_default_fallback
  core_fallback_threshold: 0.5
  enable_fallback_prediction: false
  max_history: 10
  name: kairon.shared.policy.KRulePolicy
