stages:
  - test

before_script:
  - echo "Stage Started for " $CI_COMMIT_REF_NAME
  - export PATH=$PATH:/usr/local/bin

test:
  tags:
    - kairon-test
  stage: test
  script:
    - python3.10 -V
    - python3.10 -m pip install virtualenv
    - python3.10 -m virtualenv env
    - source env/bin/activate
    - python3.10 -m pip install --upgrade pip
    - export PIP_DEFAULT_TIMEOUT=100
    - python3.10 -m pip --default-timeout=100 install -U -r requirements/dev.txt
    - python3.10 -m nltk.downloader averaged_perceptron_tagger
    - python3.10 -m nltk.downloader punkt
    - python3.10 -m nltk.downloader stopwords
    - python3.10 -m nltk.downloader omw-1.4
    - python3.10 -m nltk.downloader wordnet
    - python3.10 -m pytest tests --html=report.html --cov=kairon --cov-report html:coverage_html --disable-warnings
    - deactivate
    - rm -r env/